# Copyright 2014 The Closure Library Authors. All Rights Reserved.
#
# Use of this source code is governed by the Apache License, Version 2.0.
# See the LICENSE file for details.

# Use new container-based infrastructure.
sudo: false

# Cache node modules across runs.
cache:
  - node_modules

install:
  - ./scripts/ci/install_closure_deps.sh

script:
  - ./scripts/ci/compile_closure.sh
  - ./scripts/ci/lint_pull_request.sh
  - travis_wait 30 ./scripts/ci/run_all_tests.sh

addons:
  sauce_connect: true

env:
  global:
    - secure: G3YiCL+uZVLv0XdMjPhczNM5k6vBBqUqsvjArQZmJmf/zKwEP49vv7ag2f//9msc4XrzXs06OzHW3tI8nq7JJnGrupTcJBeZ6Vcg06Z1W2pG8/dSNJ0dRC493ICIBpU8VW2moYF1aDdY1oktdII7xQ705nBcRJ9VcLqG1Km2BpY=
    - secure: kqXS2ih32mv1Xw0l8bs+QeMRc7wdVxVMzsZ7LdtLbTfAKdHlF/FyshLXpbLjPJDdIndyBZfH1U+KJI2SfqRhyo/kvuiOlz0okeh+paRumCjradPYlTXkr/Ji91gSRa/HObupEoYOKoERjZlK/eH9FXYBKx63LSwV6qiAppQdiSo=
